services:
  postgres_clients:
    image: postgres:16
    container_name: postgres_clients
    environment:
      POSTGRES_USER: client_user
      POSTGRES_PASSWORD: client_pass
      POSTGRES_DB: clients_db
    ports:
      - "5544:5432"  # Host:Container
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin_clients:
    image: dpage/pgadmin4
    container_name: pgadmin_clients
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_pass
    ports:
      - "8080:80"

  mongo_posts:
    image: mongo:7
    container_name: mongo_posts
    environment:
      MONGO_INITDB_ROOT_USERNAME: posts_admin
      MONGO_INITDB_ROOT_PASSWORD: posts_pass
      MONGO_INITDB_DATABASE: posts_db
    ports:
      - "27019:27017"
    volumes:
      - mongodata:/data/db

  mongo_express_posts:
    image: mongo-express
    container_name: mongo_express_posts
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: posts_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: posts_pass
      ME_CONFIG_MONGODB_SERVER: mongo_posts
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    ports:
      - "8083:8081"

volumes:
  pgdata:
  mongodata:
